version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./chat.db:/app/chat.db
    environment:
      - SECRET_KEY=change-me
    restart: unless-stopped
